version: '3.8'

services:
  backend:
    build: .
    container_name: backendproject2_container
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped